apiVersion: v1
kind: ConfigMap
metadata:
  name: node-sentinel-nodejs
data:
  REDIS_SENTINELS: redis-sentinel-node-0.redis.svc.cluster.local:26379,redis-sentinel-node-1.redis.svc.cluster.local:26379,redis-sentinel-node-2.redis.svc.cluster.local:26379
  CLUSTER_NAME: "local"
  REDIS_DB_NUMBER: "2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-sentinel-java-consoleapp
data:
  REDIS_SENTINELS: "redis://redis-sentinel-node-0.redis.svc.cluster.local:26379,redis://redis-sentinel-node-1.redis.svc.cluster.local:26379,redis://redis-sentinel-node-2.redis.svc.cluster.local:26379"
  MASTER_NAME: "local"
  DATABASE: "1"
  READ_MODE: "MASTER"
