apiVersion: v1
kind: ConfigMap
metadata:
  name: node-sentinel
data:
  REDIS_SENTINELS: redis-sentinel-node-0.redis.svc.cluster.local:26379,redis-sentinel-node-1.redis.svc.cluster.local:26379,redis-sentinel-node-2.redis.svc.cluster.local:26379
  CLUSTER_NAME: "local"
  REDIS_DB_NUMBER: "3"
