global:
  storageClass: ~
architecture: replication
auth:
  enabled: true
  sentinel: true
  existingSecret: "redis-password"
  existingSecretPasswordKey: "REDIS_PASSWORD"
sentinel:
  enabled: true
  masterSet: local
  resources:
    requests:
      memory: 512Mi
      cpu: 400m
    limits:
      memory: 1Gi
      cpu: 800m
  persistence:
    enabled: true
    size: 50Gi
  service:
    type: NodePort
    nodePorts:
      sentinel: "30300"
      redis: "30400"
replica:
  resources:
    requests:
      memory: 512Mi
      cpu: 400m
    limits:
      memory: 1Gi
      cpu: 800m
  persistence:
    enabled: true
    size: 50Gi
master:
  resources:
    requests:
      memory: 512Mi
      cpu: 400m
    limits:
      memory: 1Gi
      cpu: 800m
  persistence:
    enabled: true
    size: 50Gi
